
name: 'dbt_observability_marts'
version: '0.0.1'

profile: 'dbt_observability_marts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_observability_marts:
    +materialized: table
    +file_format: delta
    +schema: observability
    sources:
      +on_schema_change: append_new_columns
    +access: public
    staging:
      +schema: observability
      +materialized: view
    intermediate:
      +schema: observability
      +materialized: view
    reporting:
      +schema: observability
      +materialized: table

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_observability_marts', 'dbt']
  - macro_namespace: dbt_utils
    search_order: ['dbt_observability_marts', 'dbt_utils']
